export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const PUSH_CATEGORY = 'PUSH_CATEGORY';
export const ADD_POST_TO_CATEGORY = 'ADD_POST_TO_CATEGORY';
